update drupal core
qlstudent@kus-HP-EliteDesk-800-G1-SFF:~/src/utah$ cd ~/src/nevada/;time cat composer.json;time composer outdated;time composer outdated drupal/*;time rm composer.lock;time composer update drupal/* webflo/drupal-core-require-dev webflo/drupal-core-strict --with-dependencies;time git status;time git add .;time git commit -S;time git pull;time git push;
{
    "name": "pantheon-systems/example-drops-8-composer",
    "description": "Install drops-8 with Composer on Pantheon.",
    "type": "project",
    "license": "MIT",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "php": ">=7.0.8",
        "composer/installers": "^1.0.20",
        "cweagans/composer-patches": "^1.0",
        "drupal-composer/drupal-scaffold": "^2.0.1",
        "drupal/config_direct_save": "^1.0",
        "drupal/config_installer": "^1.0",
        "drupal/console": "^1",
        "drupal/core": "^8",
        "drupal/simple_block": "^1.0@beta",
        "drush/drush": "~8",
        "rvtraveller/qs-composer-installer": "^1.1",
        "drush-ops/behat-drush-endpoint": "^0.0.5",
        "pantheon-systems/quicksilver-pushback": "~1",
        "webflo/drupal-core-strict": "^8"
    },
    "require-dev": {
        "mikey179/vfsstream": "^1.2",
        "behat/behat": "3.*",
        "behat/mink": "^1.7",
        "behat/mink-extension": "^2.2",
        "behat/mink-goutte-driver": "^1.2",
        "jcalderonzumba/gastonjs": "^1.0.2",
        "jcalderonzumba/mink-phantomjs-driver": "^0.3.1",
        "drupal/drupal-extension": "^3.1",
        "phpunit/phpunit": "^4.8",
        "symfony/css-selector": "^2.8"
    },
    "conflict": {
            "drupal/drupal": "*"
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ]
    },
    "scripts": {
        "build-assets": [
            "@prepare-for-pantheon",
            "composer install --optimize-autoloader --no-dev"
        ],
        "lint": "find web/modules/custom web/themes/custom -name '*.php' -exec php -l {} \\;",
        "code-sniff": "echo 'No code sniff step defined.'",
        "unit-test": "echo 'No unit test step defined.'",
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "prepare-for-pantheon": "DrupalProject\\composer\\ScriptHandler::prepareForPantheon",
        "post-install-cmd": [
            "@drupal-scaffold",
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles",
            "find .circleci/scripts/pantheon/ -type f | xargs chmod 755",
            "find tests/scripts/ -type f | xargs chmod 755"
        ],
        "post-create-project-cmd": [
            "@drupal-scaffold",
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        },
        "build-env": {
            "install-cms": [
                "drush site-install standard --account-mail={account-mail} --account-name={account-name} --account-pass={account-pass} --site-mail={site-mail} --site-name={site-name} --yes",
                "drush pm-enable config_direct_save simple_block --yes",
                "drush pm-uninstall block_content --yes"
            ],
            "export-configuration": "drush config-export --yes"
        },
        "drupal-scaffold": {
            "source": "https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/{version}/{path}",
            "includes": [
                "sites/default/default.services.pantheon.preproduction.yml",
                "sites/default/settings.pantheon.php"
            ],
            "excludes": [
                ".csslintrc",
                ".editorconfig",
                ".eslintignore",
                ".eslintrc.json",
                ".htaccess",
                "web.config"
            ]
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "platform": {
            "php": "7.0.8"
        }
    }
}

real	0m0.069s
user	0m0.001s
sys	0m0.000s
alchemy/zippy                         0.4.3       0.4.9       Zippy, the archive manager companion
behat/behat                           v3.4.3      v3.5.0      Scenario-oriented BDD framework for PHP 5.3
behat/mink-browserkit-driver          v1.3.2      1.3.3       Symfony2 BrowserKit driver for Mink framework
consolidation/annotated-command       2.8.3       2.8.5       Initialize Symfony Console commands from annotated command class methods.
consolidation/output-formatters       3.2.0       3.2.1       Format text by applying transformations provided by plug-in formatters.
cweagans/composer-patches             1.6.4       1.6.5       Provides a way to patch Composer packages.
dflydev/dot-access-configuration      v1.0.2      v1.0.3      Given a deep data structure representing a configuration, access configuration by do...
dflydev/dot-access-data               v1.1.0      v2.0.0      Given a deep data structure, access data by dot notation.
doctrine/annotations                  v1.2.7      v1.4.0      Docblock Annotations Parser
doctrine/cache                        v1.6.1      v1.6.2      Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.3.0      v1.4.0      Collections Abstraction library
doctrine/common                       v2.6.2      v2.7.3      Common Library for Doctrine projects
doctrine/inflector                    v1.1.0      v1.2.0      Common String Manipulations with regard to casing and singular/plural rules.
drupal-composer/drupal-scaffold       2.4.0       2.5.4       Composer Plugin for updating the Drupal scaffold files when using drupal/core
drupal/config_installer               1.7.0       1.8.0
drupal/core                           8.5.5       8.6.1       Drupal is an open source content management platform powering millions of websites a...
drush-ops/behat-drush-endpoint        0.0.5       1.0.0       Drush commandfile for use with drupal/drupal-driver.
drush/drush                           8.1.16      9.4.0       Drush is a command line shell and scripting interface for Drupal, a veritable Swiss ...
egulias/email-validator               1.2.14      2.1.5       A library for validating emails
fabpot/goutte                         v3.2.2      v3.2.3      A simple PHP Web Scraper
guzzlehttp/guzzle                     6.3.0       6.3.3       Guzzle is a PHP HTTP client library
nikic/php-parser                      v4.0.1      v4.0.3      A PHP parser written in PHP
paragonie/random_compat               v2.0.11     v9.99.99    PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/type-resolver           0.4.0       0.5.1
phpspec/prophecy                      1.7.6       1.8.0       Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             2.2.4       5.3.2       Library that provides collection, processing, and rendering functionality for PHP co...
phpunit/php-token-stream              1.4.12      2.0.2       Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       4.8.36      6.5.13      The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          2.3.8       5.0.10      Mock Object library for PHPUnit
psy/psysh                             v0.9.3      v0.9.8      An interactive shell for modern PHP.
sebastian/comparator                  1.2.4       2.1.3       Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.3       2.0.1       Diff implementation
sebastian/environment                 1.3.8       3.1.0       Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.2       3.1.0       Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1       2.0.0       Snapshotting of global state
sebastian/recursion-context           1.0.5       3.0.0       Provides functionality to recursively process PHP variables
sebastian/version                     1.0.6       2.0.1       Library that helps with managing the version number of Git-hosted PHP projects
symfony-cmf/routing                   1.4.1       2.0.3       Extends the Symfony2 routing component for dynamic routes and chaining several routers
symfony/browser-kit                   v3.4.8      v3.4.15     Symfony BrowserKit Component
symfony/class-loader                  v3.4.4      v3.4.15     Symfony ClassLoader Component
symfony/config                        v3.4.8      v3.4.15     Symfony Config Component
symfony/console                       v3.4.4      v3.4.15     Symfony Console Component
symfony/css-selector                  v2.8.38     v3.4.15     Symfony CssSelector Component
symfony/debug                         v3.4.4      v3.4.15     Symfony Debug Component
symfony/dependency-injection          v3.4.4      v3.4.15     Symfony DependencyInjection Component
symfony/dom-crawler                   v3.4.8      v3.4.15     Symfony DomCrawler Component
symfony/event-dispatcher              v3.4.4      v3.4.15     Symfony EventDispatcher Component
symfony/filesystem                    v3.4.8      v3.4.15     Symfony Filesystem Component
symfony/finder                        v3.4.8      v3.4.15     Symfony Finder Component
symfony/http-foundation               v3.4.4      v3.4.15     Symfony HttpFoundation Component
symfony/http-kernel                   v3.4.4      v3.4.15     Symfony HttpKernel Component
symfony/polyfill-iconv                v1.6.0      v1.9.0      Symfony polyfill for the Iconv extension
symfony/polyfill-mbstring             v1.6.0      v1.9.0      Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                v1.6.0      v1.9.0      Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/process                       v3.4.4      v3.4.15     Symfony Process Component
symfony/psr-http-message-bridge       v1.0.2      v1.1.0      PSR HTTP message bridge
symfony/routing                       v3.4.4      v3.4.15     Symfony Routing Component
symfony/serializer                    v3.4.4      v3.4.15     Symfony Serializer Component
symfony/translation                   v3.4.4      v3.4.15     Symfony Translation Component
symfony/validator                     v3.4.4      v3.4.15     Symfony Validator Component
symfony/var-dumper                    v3.4.8      v3.4.15     Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.4.5      v3.4.15     Symfony Yaml Component
twig/twig                             v1.35.0     v2.5.0      Twig, the flexible, fast, and secure template language for PHP
webflo/drupal-core-strict             8.5.2       8.6.1       Locked core dependencies
zendframework/zend-diactoros          1.4.1       1.8.6       PSR HTTP Message implementations
zendframework/zend-escaper            2.5.2       2.6.0
zendframework/zend-feed               2.7.0       2.10.3      provides functionality for consuming RSS and Atom feeds
zendframework/zend-stdlib             3.0.1       3.2.1

real	4m13.610s
user	0m3.347s
sys	0m30.313s
drupal/config_installer      1.7.0       1.8.0
drupal/core                  8.5.5       8.6.1       Drupal is an open source content management platform powering millions of websites and applic...

real	1m43.032s
user	0m0.953s
sys	0m28.391s

real	0m0.050s
user	0m0.002s
sys	0m0.000s
Package "webflo/drupal-core-require-dev" listed for update is not installed. Ignoring.
Dependency "composer/installers" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 20 updates, 0 removals
  - Installing symfony/polyfill-ctype (v1.8.0): Loading from cache
  - Updating twig/twig (v1.35.0 => v1.35.3): Loading from cache
  - Updating symfony/yaml (v3.4.5 => v3.4.14): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.6.0 => v1.8.0): Loading from cache
  - Updating symfony/translation (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/validator (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/serializer (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/routing (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/polyfill-php70 (v1.6.0 => v1.8.0): Loading from cache
  - Updating symfony/http-foundation (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/process (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/polyfill-iconv (v1.6.0 => v1.8.0): Loading from cache
  - Updating symfony/event-dispatcher (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/debug (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/http-kernel (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/dependency-injection (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/console (v3.4.4 => v3.4.14): Loading from cache
  - Updating symfony/class-loader (v3.4.4 => v3.4.14): Loading from cache
  - Updating drupal/core (8.5.5 => 8.6.1): Loading from cache
  - Updating drupal/config_installer (1.7.0 => 1.8.0): Loading from cache
Writing lock file
Generating optimized autoload files
Downloading (100%)Downloading (100%)Downloading (100%)Downloading (100%)Downloading (100%)Downloading (100%)Downloading (100%)Downloading (connecting.Downloading (100%)Downloading (100%)Downloading (100%)Downloading (100%)Downloading (100%)> DrupalProject\composer\ScriptHandler::createRequiredFiles
> find .circleci/scripts/pantheon/ -type f | xargs chmod 755
> find tests/scripts/ -type f | xargs chmod 755

real	21m18.120s
user	0m22.546s
sys	2m29.212s
On branch update-852
Your branch is up to date with 'origin/update-852'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   composer.lock

no changes added to commit (use "git add" and/or "git commit -a")

real	0m0.890s
user	0m0.007s
sys	0m0.000s

real	0m0.024s
user	0m0.006s
sys	0m0.003s
error: gpg failed to sign the data
fatal: failed to write commit object

real	0m18.508s
user	0m0.033s
sys	0m0.009s
Already up to date.

real	0m0.341s
user	0m0.037s
sys	0m0.005s
Everything up-to-date
Everything up-to-date

real	0m1.683s
user	0m0.051s
sys	0m0.004s